! (C) Copyright 2015- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
!
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.




MODULE RADIATION_SCHEME_LAYER_MOD

IMPLICIT NONE

PRIVATE
PUBLIC :: RADIATION_SCHEME_LAYER
CONTAINS

SUBROUTINE RADIATION_SCHEME_LAYER &
     & (YRADIATION, ZRGP_FIELDS, NGPTOT, NRPROMA, NFLEVG, &
     &  NFSD, KAEROSOL, PSOLAR_IRRADIANCE, ISEED)

! Modules from ifs or ifsaux libraries
USE RADIATION_SETUP , ONLY : TRADIATION
USE PARKIND1        , ONLY : JPIM, JPRB
USE RADINTG_ZRGP_MOD, ONLY : RADINTG_ZRGP_TYPE

IMPLICIT NONE

! INPUT ARGUMENTS

TYPE(TRADIATION)   ,INTENT(IN), TARGET :: YRADIATION
TYPE(RADINTG_ZRGP_TYPE), INTENT(INOUT) :: ZRGP_FIELDS

! *** Array dimensions and ranges
INTEGER(KIND=JPIM),INTENT(IN)   :: NGPTOT   ! Number of columns
INTEGER(KIND=JPIM),INTENT(IN)   :: NRPROMA   ! Number of columns
INTEGER(KIND=JPIM),INTENT(IN)   :: NFLEVG   ! Number of levels
INTEGER(KIND=JPIM),INTENT(IN)   :: NFSD
INTEGER(KIND=JPIM),INTENT(IN)   :: KAEROSOL ! Number of aerosol types

! *** Single-level fields
REAL(KIND=JPRB),   INTENT(IN)   :: PSOLAR_IRRADIANCE ! (W m-2)

INTEGER, OPTIONAL, INTENT(IN)   :: ISEED(:,:)

IF (YRADIATION%YRERAD%LECRAD_ON_GPU) THEN
  CALL RADIATION_SCHEME_LAYER_LOKI( &
      & YRADIATION, ZRGP_FIELDS, NGPTOT, NRPROMA, NFLEVG, &
      & NFSD, KAEROSOL, PSOLAR_IRRADIANCE, ISEED=ISEED )
ELSE
  CALL RADIATION_SCHEME_LAYER_PARALLEL( &
      & YRADIATION, ZRGP_FIELDS, NGPTOT, NRPROMA, NFLEVG, &
      & NFSD, KAEROSOL, PSOLAR_IRRADIANCE, ISEED=ISEED )
ENDIF

END SUBROUTINE RADIATION_SCHEME_LAYER

SUBROUTINE RADIATION_SCHEME_LAYER_PARALLEL &
     & (YRADIATION, ZRGP_FIELDS, NGPTOT, NRPROMA, NFLEVG, &
     &  NFSD, KAEROSOL, PSOLAR_IRRADIANCE, ISEED)

USE FIELD_MODULE
USE FIELD_FACTORY_MODULE

! Modules from ifs or ifsaux libraries
USE RADIATION_SETUP , ONLY : TRADIATION
USE PARKIND1        , ONLY : JPIM, JPRB
USE YOMHOOK         , ONLY : LHOOK, DR_HOOK, JPHOOK
USE RADINTG_ZRGP_MOD, ONLY : RADINTG_ZRGP_TYPE
USE RADIATION_FIELD_TYPE_MODULE,    ONLY : SINGLE_LEVEL_FIELD_TYPE,    &
                                         & THERMODYNAMICS_FIELD_TYPE,  &
                                         & GAS_FIELD_TYPE,             &
                                         & CLOUD_FIELD_TYPE,           &
                                         & AEROSOL_FIELD_TYPE,         &
                                         & FLUX_FIELD_TYPE
! Modules from radiation
USE RADIATION_SINGLE_LEVEL,         ONLY: SINGLE_LEVEL_TYPE
USE RADIATION_THERMODYNAMICS,       ONLY: THERMODYNAMICS_TYPE
USE RADIATION_GAS,                  ONLY: GAS_TYPE
USE RADIATION_CLOUD,                ONLY: CLOUD_TYPE
USE RADIATION_AEROSOL,              ONLY: AEROSOL_TYPE
USE RADIATION_FLUX,                 ONLY: FLUX_TYPE

IMPLICIT NONE

! INPUT ARGUMENTS

TYPE(TRADIATION)   ,INTENT(IN), TARGET :: YRADIATION
TYPE(RADINTG_ZRGP_TYPE), INTENT(INOUT) :: ZRGP_FIELDS

! *** Array dimensions and ranges
INTEGER(KIND=JPIM),INTENT(IN)   :: NGPTOT   ! Number of columns
INTEGER(KIND=JPIM),INTENT(IN)   :: NRPROMA   ! Number of columns
INTEGER(KIND=JPIM),INTENT(IN)   :: NFLEVG   ! Number of levels
INTEGER(KIND=JPIM),INTENT(IN)   :: NFSD
INTEGER(KIND=JPIM),INTENT(IN)   :: KAEROSOL ! Number of aerosol types

! *** Single-level fields
REAL(KIND=JPRB),   INTENT(IN)   :: PSOLAR_IRRADIANCE ! (W m-2)

INTEGER, OPTIONAL, INTENT(IN)   :: ISEED(:,:)

INTEGER(KIND=JPIM) :: KIDIA, KFDIA, IBL, JKGLO, NBLKS

! Dummies for IFS config values
LOGICAL :: LSPPRAD, LRAYFM, LEPO3RA
LOGICAL, PARAMETER :: LDEBUG = .false.

! Ecrad derived types and FIELD API wrapper types
TYPE(SINGLE_LEVEL_FIELD_TYPE) :: SINGLE_LEVEL_FIELD
TYPE(SINGLE_LEVEL_TYPE) :: SINGLE_LEVEL
TYPE(THERMODYNAMICS_FIELD_TYPE) :: THERMODYNAMICS_FIELD
TYPE(THERMODYNAMICS_TYPE) :: THERMODYNAMICS
TYPE(GAS_FIELD_TYPE) :: GAS_FIELD
TYPE(GAS_TYPE) :: GAS
TYPE(CLOUD_FIELD_TYPE) :: YLCLOUD_FIELD
TYPE(CLOUD_TYPE) :: YLCLOUD
TYPE(AEROSOL_FIELD_TYPE) :: AEROSOL_FIELD
TYPE(AEROSOL_TYPE) :: AEROSOL
TYPE(FLUX_FIELD_TYPE) :: FLUX_FIELD
TYPE(FLUX_TYPE) :: FLUX

! Field pointers for each field in ZRGP
CLASS(FIELD_2RB), POINTER :: F_igi => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_igi(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_imu0 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_imu0(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iamu0 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iamu0(:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iemiss => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iemiss(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_its => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_its(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_islm => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_islm(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iccnl => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iccnl(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iccno => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iccno(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_ibas => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ibas(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_itop => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_itop(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_igelam => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_igelam(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_igemu => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_igemu(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iclon => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iclon(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_islon => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_islon(:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iald => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iald(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ialp => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ialp(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iti => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iti(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ipr => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ipr(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iqs => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iqs(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iwv => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iwv(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iclc => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iclc(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ilwa => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ilwa(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iiwa => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iiwa(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iswa => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iswa(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_irwa => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_irwa(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_irra => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_irra(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_idp => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_idp(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ioz => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ioz(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iecpo3 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iecpo3(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ihpr => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ihpr(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iaprs => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iaprs(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ihti => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ihti(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ire_liq => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ire_liq(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ire_ice => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ire_ice(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ioverlap => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ioverlap(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iaero => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iaero(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_ifrsod => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrsod(:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ifrted => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrted(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_ifrsodc => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrsodc(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_ifrtedc => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrtedc(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iemit => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iemit(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_isudu => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_isudu(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iuvdf => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iuvdf(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iparf => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iparf(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iparcf => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iparcf(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_itincf => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_itincf(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_ifdir => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifdir(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_ifdif => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifdif(:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_icdir => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_icdir(:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ilwderivative => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ilwderivative(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iswdirectband => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iswdirectband(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iswdiffuseband => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iswdiffuseband(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ifrso => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrso(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iswfc => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iswfc(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ifrth => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrth(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ilwfc => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ilwfc(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iaer => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iaer(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iico2 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iico2(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iich4 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iich4(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iin2o => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iin2o(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ino2 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ino2(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ic11 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ic11(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ic12 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ic12(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ic22 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ic22(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_icl4 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_icl4(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_igix => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_igix(:) => NULL()

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "radiation_scheme.intfb.h"

IF (LHOOK) CALL DR_HOOK('RADIATION_SCHEME_LAYER_PARALLEL',0,ZHOOK_HANDLE)

ASSOCIATE(YDERAD=>YRADIATION%YRERAD, RAD_CONFIG=>YRADIATION%RAD_CONFIG)
ASSOCIATE(LDIAGFORCING=>YDERAD%LDIAGFORCING, LAPPROXLWUPDATE=>YDERAD%LAPPROXLWUPDATE, &
    & LAPPROXSWUPDATE=>YDERAD%LAPPROXSWUPDATE, NRADAER=>RAD_CONFIG%N_AEROSOL_TYPES)

LSPPRAD=.FALSE.
LRAYFM=.FALSE.
LEPO3RA=.FALSE.

NBLKS = (NGPTOT-1)/NRPROMA + 1
CALL SINGLE_LEVEL_FIELD%INIT(NBLKS, NRPROMA, YRADIATION%YRERAD%NSW, YRADIATION%YRERAD%NLWEMISS, &
     &                      USE_SW_ALBEDO_DIRECT=.TRUE.)
CALL THERMODYNAMICS_FIELD%INIT(NBLKS, NRPROMA, NFLEVG, USE_H2O_SAT=.TRUE.)
CALL GAS_FIELD%INIT(NBLKS, NRPROMA, NFLEVG)
CALL YLCLOUD_FIELD%INIT(NBLKS, NRPROMA, NFLEVG, FRAC_STD=YRADIATION%YRERAD%RCLOUD_FRAC_STD)
IF (YRADIATION%YRERAD%NAERMACC == 1) THEN
  CALL AEROSOL_FIELD%INIT(NBLKS, NRPROMA, 1, NFLEVG, KAEROSOL) ! MACC aerosols
ELSE
  CALL AEROSOL_FIELD%INIT(NBLKS, NRPROMA, 1, NFLEVG, 6) ! Tegen climatology
ENDIF
CALL FLUX_FIELD%INIT(NBLKS, YRADIATION%RAD_CONFIG, 1, NRPROMA, NFLEVG)

!$OMP PARALLEL &
!$OMP&  PRIVATE(KIDIA,KFDIA,IBL,&
!$OMP&    F_igi,F_imu0,F_iamu0,F_iemiss,F_its, &
!$OMP&    F_islm,F_iccnl,F_iccno,F_ibas,F_itop, &
!$OMP&    F_igelam,F_igemu,F_iclon,F_islon,F_iald, &
!$OMP&    F_ialp,F_iti,F_ipr,F_iqs,F_iwv, &
!$OMP&    F_iclc,F_ilwa,F_iiwa,F_iswa,F_irwa, &
!$OMP&    F_irra,F_idp,F_ioz,F_iecpo3,F_ihpr, &
!$OMP&    F_iaprs,F_ihti,F_ire_liq,F_ire_ice,F_ioverlap, &
!$OMP&    F_iaero,F_ifrsod,F_ifrted,F_ifrsodc,F_ifrtedc, &
!$OMP&    F_iemit,F_isudu,F_iuvdf,F_iparf,F_iparcf, &
!$OMP&    F_itincf,F_ifdir,F_ifdif,F_icdir,F_ilwderivative, &
!$OMP&    F_iswdirectband,F_iswdiffuseband,F_ifrso,F_iswfc,F_ifrth, &
!$OMP&    F_ilwfc,F_iaer,F_iico2,F_iich4,F_iin2o, &
!$OMP&    F_ino2,F_ic11,F_ic12,F_ic22,F_icl4, &
!$OMP&    F_igix &
!$OMP&  ) &
!$OMP&  PRIVATE(&
!$OMP&    P_igi,P_imu0,P_iamu0,P_iemiss,P_its, &
!$OMP&    P_islm,P_iccnl,P_iccno,P_ibas,P_itop, &
!$OMP&    P_igelam,P_igemu,P_iclon,P_islon,P_iald, &
!$OMP&    P_ialp,P_iti,P_ipr,P_iqs,P_iwv, &
!$OMP&    P_iclc,P_ilwa,P_iiwa,P_iswa,P_irwa, &
!$OMP&    P_irra,P_idp,P_ioz,P_iecpo3,P_ihpr, &
!$OMP&    P_iaprs,P_ihti,P_ire_liq,P_ire_ice,P_ioverlap, &
!$OMP&    P_iaero,P_ifrsod,P_ifrted,P_ifrsodc,P_ifrtedc, &
!$OMP&    P_iemit,P_isudu,P_iuvdf,P_iparf,P_iparcf, &
!$OMP&    P_itincf,P_ifdir,P_ifdif,P_icdir,P_ilwderivative, &
!$OMP&    P_iswdirectband,P_iswdiffuseband,P_ifrso,P_iswfc,P_ifrth, &
!$OMP&    P_ilwfc,P_iaer,P_iico2,P_iich4,P_iin2o, &
!$OMP&    P_ino2,P_ic11,P_ic12,P_ic22,P_icl4, &
!$OMP&    P_igix &
!$OMP&  ) &
!$OMP&  FIRSTPRIVATE(&
!$OMP&    SINGLE_LEVEL_FIELD, SINGLE_LEVEL, &
!$OMP&    THERMODYNAMICS_FIELD, THERMODYNAMICS, &
!$OMP&    GAS_FIELD, GAS, &
!$OMP&    YLCLOUD_FIELD, YLCLOUD, &
!$OMP&    AEROSOL_FIELD, AEROSOL, &
!$OMP&    FLUX_FIELD, FLUX &
!$OMP&  )

CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 1, F_igi)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 2, F_imu0)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 3, F_iamu0)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 4, F_iemiss)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 5, F_its)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 6, F_islm)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 7, F_iccnl)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 8, F_iccno)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 9, F_ibas)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 10, F_itop)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 11, F_igelam)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 12, F_igemu)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 13, F_iclon)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 14, F_islon)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 15, F_iald)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 16, F_ialp)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 17, F_iti)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 18, F_ipr)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 19, F_iqs)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 20, F_iwv)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 21, F_iclc)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 22, F_ilwa)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 23, F_iiwa)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 24, F_iswa)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 25, F_irwa)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 26, F_irra)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 27, F_idp)
IF(lrayfm) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 28, F_ioz)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 29, F_iecpo3)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 30, F_ihpr)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 31, F_iaprs)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 32, F_ihti)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 33, F_ire_liq)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 34, F_ire_ice)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 35, F_ioverlap)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 36, F_iaero)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 37, F_ifrsod)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 38, F_ifrted)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 39, F_ifrsodc)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 40, F_ifrtedc)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 41, F_iemit)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 42, F_isudu)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 43, F_iuvdf)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 44, F_iparf)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 45, F_iparcf)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 46, F_itincf)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 47, F_ifdir)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 48, F_ifdif)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 49, F_icdir)
IF(lapproxlwupdate) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 50, F_ilwderivative)
IF(lapproxlwupdate) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 51, F_iswdirectband)
IF(lapproxlwupdate) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 52, F_iswdiffuseband)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 53, F_ifrso)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 54, F_iswfc)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 55, F_ifrth)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 56, F_ilwfc)
IF(ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 57, F_iaer)
IF(ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 58, F_ioz)
IF(ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 59, F_iico2)
IF(ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 60, F_iich4)
IF(ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 61, F_iin2o)
IF(ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 62, F_ino2)
IF(ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 63, F_ic11)
IF(ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 64, F_ic12)
IF(ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 65, F_ic22)
IF(ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 66, F_icl4)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 67, F_igix)
IF(.not.ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 68, F_iaer)
IF(.not.(ldiagforcing.or.lrayfm)) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 69, F_ioz)
IF(.not.ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 70, F_iico2)
IF(.not.ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 71, F_iich4)
IF(.not.ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 72, F_iin2o)
IF(.not.ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 73, F_ino2)
IF(.not.ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 74, F_ic11)
IF(.not.ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 75, F_ic12)
IF(.not.ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 76, F_ic22)
IF(.not.ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 77, F_icl4)

!$OMP DO SCHEDULE(DYNAMIC,1)
DO JKGLO=1,NGPTOT,NRPROMA
    KIDIA=1
    KFDIA=MIN(NRPROMA,NGPTOT-JKGLO+1)
    IBL=(JKGLO-1)/NRPROMA+1

    ! Update radiation field type view pointers
    CALL SINGLE_LEVEL_FIELD%UPDATE_VIEW(IBL)
    CALL SINGLE_LEVEL_FIELD%UPDATE_SINGLE_LEVEL(SINGLE_LEVEL)
    CALL THERMODYNAMICS_FIELD%UPDATE_VIEW(IBL)
    CALL THERMODYNAMICS_FIELD%UPDATE_THERMODYNAMICS(THERMODYNAMICS)
    CALL GAS_FIELD%UPDATE_VIEW(IBL)
    CALL GAS_FIELD%UPDATE_GAS(GAS)
    CALL YLCLOUD_FIELD%UPDATE_VIEW(IBL)
    CALL YLCLOUD_FIELD%UPDATE_CLOUD(YLCLOUD)
    CALL AEROSOL_FIELD%UPDATE_VIEW(IBL)
    CALL AEROSOL_FIELD%UPDATE_AEROSOL(AEROSOL)
    CALL FLUX_FIELD%UPDATE_VIEW(IBL)
    CALL FLUX_FIELD%UPDATE_FLUX(FLUX)

    P_iamu0 => F_iamu0%GET_VIEW(IBL)
    P_its => F_its%GET_VIEW(IBL)
    P_iald => F_iald%GET_VIEW(IBL)
    P_ialp => F_ialp%GET_VIEW(IBL)
    P_iemiss => F_iemiss%GET_VIEW(IBL)
    P_iccnl => F_iccnl%GET_VIEW(IBL)
    P_iccno => F_iccno%GET_VIEW(IBL)
    P_igelam => F_igelam%GET_VIEW(IBL)
    P_igemu => F_igemu%GET_VIEW(IBL)
    P_islm => F_islm%GET_VIEW(IBL)
    P_ipr => F_ipr%GET_VIEW(IBL)
    P_iti => F_iti%GET_VIEW(IBL)
    P_iaprs => F_iaprs%GET_VIEW(IBL)
    P_ihti => F_ihti%GET_VIEW(IBL)
    P_iwv => F_iwv%GET_VIEW(IBL)
    P_iico2 => F_iico2%GET_VIEW(IBL)
    P_iich4 => F_iich4%GET_VIEW(IBL)
    P_iin2o => F_iin2o%GET_VIEW(IBL)
    P_ino2 => F_ino2%GET_VIEW(IBL)
    P_ic11 => F_ic11%GET_VIEW(IBL)
    P_ic12 => F_ic12%GET_VIEW(IBL)
    P_ic22 => F_ic22%GET_VIEW(IBL)
    P_icl4 => F_icl4%GET_VIEW(IBL)
    P_ioz => F_ioz%GET_VIEW(IBL)
    P_iclc => F_iclc%GET_VIEW(IBL)
    P_ilwa => F_ilwa%GET_VIEW(IBL)
    P_iiwa => F_iiwa%GET_VIEW(IBL)
    P_irwa => F_irwa%GET_VIEW(IBL)
    P_iswa => F_iswa%GET_VIEW(IBL)
    P_iaer => F_iaer%GET_VIEW(IBL)
    P_iaero => F_iaero%GET_VIEW(IBL)
    P_iaero => F_iaero%GET_VIEW(IBL)
    P_ifrso => F_ifrso%GET_VIEW(IBL)
    P_ifrth => F_ifrth%GET_VIEW(IBL)
    P_iswfc => F_iswfc%GET_VIEW(IBL)
    P_ilwfc => F_ilwfc%GET_VIEW(IBL)
    P_ifrsod => F_ifrsod%GET_VIEW(IBL)
    P_ifrted => F_ifrted%GET_VIEW(IBL)
    P_ifrsodc => F_ifrsodc%GET_VIEW(IBL)
    P_ifrtedc => F_ifrtedc%GET_VIEW(IBL)
    P_ifdir => F_ifdir%GET_VIEW(IBL)
    P_icdir => F_icdir%GET_VIEW(IBL)
    P_isudu => F_isudu%GET_VIEW(IBL)
    P_iuvdf => F_iuvdf%GET_VIEW(IBL)
    P_iparf => F_iparf%GET_VIEW(IBL)
    P_iparcf => F_iparcf%GET_VIEW(IBL)
    P_itincf => F_itincf%GET_VIEW(IBL)
    P_iemit => F_iemit%GET_VIEW(IBL)
    P_ilwderivative => F_ilwderivative%GET_VIEW(IBL)
    P_iswdiffuseband => F_iswdiffuseband%GET_VIEW(IBL)
    P_iswdirectband => F_iswdirectband%GET_VIEW(IBL)
    P_ire_liq => F_ire_liq%GET_VIEW(IBL)
    P_ire_ice => F_ire_ice%GET_VIEW(IBL)
    P_ioverlap => F_ioverlap%GET_VIEW(IBL)

    ! Call the ECRAD radiation scheme
    CALL RADIATION_SCHEME &
        & (YRADIATION, &
        &  KIDIA, KFDIA, NRPROMA, &                       ! startcol, endcol, ncol
        &  NFLEVG, KAEROSOL, &
        &  PSOLAR_IRRADIANCE, &                               ! solar_irrad
        &  P_IAMU0, P_ITS, P_IALD, P_IALP, &
        &  P_IEMISS, &
        &  P_ICCNL, P_ICCNO ,&
        &  P_IGELAM,P_IGEMU, P_ISLM, &
        &  P_IPR, P_ITI, &
        &  P_IAPRS,P_IHTI, &
        &  P_IWV,P_IICO2,P_IICH4,P_IIN2O, &
        &  P_INO2,P_IC11,P_IC12, P_IC22, &
        &  P_ICL4,P_IOZ, &
        &  P_ICLC,P_ILWA,P_IIWA,P_IRWA, &
        &  P_ISWA, &
        &  P_IAER, P_IAERO, &
        ! Flux outputs
        &  P_IFRSO,P_IFRTH,P_ISWFC,P_ILWFC,&
        &  P_IFRSOD,P_IFRTED, &
        &  P_IFRSODC,P_IFRTEDC,&
        &  P_IFDIR,P_ICDIR,P_ISUDU, &
        &  P_IUVDF,P_IPARF, &
        &  P_IPARCF,P_ITINCF, &
        &  P_IEMIT,P_ILWDERIVATIVE, &
        &  P_ISWDIFFUSEBAND,P_ISWDIRECTBAND &
        &, SINGLE_LEVEL &
        &, THERMODYNAMICS &
        &, GAS &
        &, YLCLOUD &
        &, AEROSOL &
        &, FLUX &
        ! OPTIONAL ARGUMENTS
#ifdef BITIDENTITY_TESTING
        &  , PRE_LIQ=P_IRE_LIQ, PRE_ICE=P_IRE_ICE &
        &  , PCLOUD_OVERLAP=P_IOVERLAP, ISEED=ISEED(:,IBL) &
#endif
        &  )

END DO
!$OMP END DO
!$OMP END PARALLEL

END ASSOCIATE
END ASSOCIATE

CALL SINGLE_LEVEL_FIELD%FINAL()
CALL THERMODYNAMICS_FIELD%FINAL()
CALL GAS_FIELD%FINAL()
CALL YLCLOUD_FIELD%FINAL()
CALL AEROSOL_FIELD%FINAL()
CALL FLUX_FIELD%FINAL()

IF (LHOOK) CALL DR_HOOK('RADIATION_SCHEME_LAYER_PARALLEL',1,ZHOOK_HANDLE)

END SUBROUTINE RADIATION_SCHEME_LAYER_PARALLEL

SUBROUTINE RADIATION_SCHEME_LAYER_LOKI &
     & (YRADIATION, ZRGP_FIELDS, NGPTOT, NRPROMA, NFLEVG, &
     &  NFSD, KAEROSOL, PSOLAR_IRRADIANCE, ISEED)

USE FIELD_MODULE, ONLY: FIELD_2RB, FIELD_3RB
USE FIELD_FACTORY_MODULE

! Modules from ifs or ifsaux libraries
USE RADIATION_SETUP , ONLY : TRADIATION
USE PARKIND1        , ONLY : JPIM, JPRB
USE YOMHOOK         , ONLY : LHOOK, DR_HOOK, JPHOOK
USE RADINTG_ZRGP_MOD, ONLY : RADINTG_ZRGP_TYPE
USE RADIATION_FIELD_TYPE_MODULE,    ONLY : SINGLE_LEVEL_FIELD_TYPE,    &
                                         & SINGLE_LEVEL_ASSOCIATE_DEVICE_POINTERS, &
                                         & THERMODYNAMICS_FIELD_TYPE,  &
                                         & THERMODYNAMICS_ASSOCIATE_DEVICE_POINTERS, &
                                         & GAS_FIELD_TYPE,             &
                                         & GAS_ASSOCIATE_DEVICE_POINTERS, &
                                         & CLOUD_FIELD_TYPE,           &
                                         & CLOUD_ASSOCIATE_DEVICE_POINTERS, &
                                         & AEROSOL_FIELD_TYPE,         &
                                         & AEROSOL_ASSOCIATE_DEVICE_POINTERS, &
                                         & FLUX_FIELD_TYPE, &
                                         & FLUX_ASSOCIATE_DEVICE_POINTERS
! Modules from radiation
USE RADIATION_SINGLE_LEVEL,         ONLY: SINGLE_LEVEL_TYPE
USE RADIATION_THERMODYNAMICS,       ONLY: THERMODYNAMICS_TYPE
USE RADIATION_GAS,                  ONLY: GAS_TYPE
USE RADIATION_CLOUD,                ONLY: CLOUD_TYPE
USE RADIATION_AEROSOL,              ONLY: AEROSOL_TYPE
USE RADIATION_FLUX,                 ONLY: FLUX_TYPE

IMPLICIT NONE

! INPUT ARGUMENTS

TYPE(TRADIATION)   ,INTENT(IN), TARGET :: YRADIATION
TYPE(RADINTG_ZRGP_TYPE), INTENT(INOUT) :: ZRGP_FIELDS

! *** Array dimensions and ranges
INTEGER(KIND=JPIM),INTENT(IN)   :: NGPTOT   ! Number of columns
INTEGER(KIND=JPIM),INTENT(IN)   :: NRPROMA   ! Number of columns
INTEGER(KIND=JPIM),INTENT(IN)   :: NFLEVG   ! Number of levels
INTEGER(KIND=JPIM),INTENT(IN)   :: NFSD
INTEGER(KIND=JPIM),INTENT(IN)   :: KAEROSOL ! Number of aerosol types

! *** Single-level fields
REAL(KIND=JPRB),   INTENT(IN)   :: PSOLAR_IRRADIANCE ! (W m-2)

INTEGER, OPTIONAL, INTENT(IN)   :: ISEED(:,:)

INTEGER(KIND=JPIM) :: KIDIA, KFDIA, IBL, JKGLO, NBLKS

! Dummies for IFS config values
LOGICAL :: LSPPRAD, LRAYFM, LEPO3RA
LOGICAL, PARAMETER :: LDEBUG = .false.

! Ecrad derived types and FIELD API wrapper types
TYPE(SINGLE_LEVEL_FIELD_TYPE) :: SINGLE_LEVEL_FIELD
TYPE(SINGLE_LEVEL_TYPE) :: SINGLE_LEVEL
TYPE(THERMODYNAMICS_FIELD_TYPE) :: THERMODYNAMICS_FIELD
TYPE(THERMODYNAMICS_TYPE) :: THERMODYNAMICS
TYPE(GAS_FIELD_TYPE) :: GAS_FIELD
TYPE(GAS_TYPE) :: GAS
TYPE(CLOUD_FIELD_TYPE) :: YLCLOUD_FIELD
TYPE(CLOUD_TYPE) :: YLCLOUD
TYPE(AEROSOL_FIELD_TYPE) :: AEROSOL_FIELD
TYPE(AEROSOL_TYPE) :: AEROSOL
TYPE(FLUX_FIELD_TYPE) :: FLUX_FIELD
TYPE(FLUX_TYPE) :: FLUX

! Field pointers for each field in ZRGP
CLASS(FIELD_2RB), POINTER :: F_igi => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_igi(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_imu0 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_imu0(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iamu0 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iamu0(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iemiss => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iemiss(:,:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_its => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_its(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_islm => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_islm(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iccnl => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iccnl(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iccno => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iccno(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_ibas => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ibas(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_itop => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_itop(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_igelam => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_igelam(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_igemu => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_igemu(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iclon => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iclon(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_islon => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_islon(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iald => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iald(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ialp => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ialp(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iti => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iti(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ipr => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ipr(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iqs => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iqs(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iwv => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iwv(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iclc => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iclc(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ilwa => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ilwa(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iiwa => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iiwa(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iswa => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iswa(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_irwa => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_irwa(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_irra => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_irra(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_idp => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_idp(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ioz => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ioz(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iecpo3 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iecpo3(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ihpr => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ihpr(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iaprs => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iaprs(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ihti => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ihti(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ire_liq => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ire_liq(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ire_ice => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ire_ice(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ioverlap => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ioverlap(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iaero => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iaero(:,:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_ifrsod => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrsod(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ifrted => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrted(:,:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_ifrsodc => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrsodc(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_ifrtedc => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrtedc(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iemit => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iemit(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_isudu => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_isudu(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iuvdf => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iuvdf(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iparf => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iparf(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_iparcf => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iparcf(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_itincf => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_itincf(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_ifdir => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifdir(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_ifdif => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifdif(:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_icdir => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_icdir(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ilwderivative => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ilwderivative(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iswdirectband => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iswdirectband(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iswdiffuseband => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iswdiffuseband(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ifrso => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrso(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iswfc => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iswfc(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ifrth => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrth(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ilwfc => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ilwfc(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iaer => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iaer(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iico2 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iico2(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iich4 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iich4(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_iin2o => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iin2o(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ino2 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ino2(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ic11 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ic11(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ic12 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ic12(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_ic22 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ic22(:,:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: F_icl4 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_icl4(:,:,:) => NULL()
CLASS(FIELD_2RB), POINTER :: F_igix => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_igix(:,:) => NULL()

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "radiation_scheme.intfb.h"

IF (LHOOK) CALL DR_HOOK('RADIATION_SCHEME_LAYER_LOKI',0,ZHOOK_HANDLE)

ASSOCIATE(YDERAD=>YRADIATION%YRERAD, RAD_CONFIG=>YRADIATION%RAD_CONFIG)
ASSOCIATE(LDIAGFORCING=>YDERAD%LDIAGFORCING, LAPPROXLWUPDATE=>YDERAD%LAPPROXLWUPDATE, &
    & LAPPROXSWUPDATE=>YDERAD%LAPPROXSWUPDATE, NRADAER=>RAD_CONFIG%N_AEROSOL_TYPES)

LSPPRAD=.FALSE.
LRAYFM=.FALSE.
LEPO3RA=.FALSE.

NBLKS = (NGPTOT-1)/NRPROMA + 1

! Initialise field types and update radiation types (pointers will be null, but reads constants)
CALL SINGLE_LEVEL_FIELD%INIT(NBLKS, NRPROMA, YRADIATION%YRERAD%NSW, YRADIATION%YRERAD%NLWEMISS, &
     &                      USE_SW_ALBEDO_DIRECT=.TRUE., ON_GPU=.TRUE.)
CALL SINGLE_LEVEL_FIELD%UPDATE_SINGLE_LEVEL(SINGLE_LEVEL)
CALL THERMODYNAMICS_FIELD%INIT(NBLKS, NRPROMA, NFLEVG, USE_H2O_SAT=.TRUE., ON_GPU=.TRUE.)
CALL THERMODYNAMICS_FIELD%UPDATE_THERMODYNAMICS(THERMODYNAMICS)
CALL GAS_FIELD%INIT(NBLKS, NRPROMA, NFLEVG, ON_GPU=.TRUE.)
CALL GAS_FIELD%UPDATE_GAS(GAS)
CALL YLCLOUD_FIELD%INIT(NBLKS, NRPROMA, NFLEVG, FRAC_STD=YRADIATION%YRERAD%RCLOUD_FRAC_STD, ON_GPU=.TRUE.)
CALL YLCLOUD_FIELD%UPDATE_CLOUD(YLCLOUD)
IF (YRADIATION%YRERAD%NAERMACC == 1) THEN
  CALL AEROSOL_FIELD%INIT(NBLKS, NRPROMA, 1, NFLEVG, KAEROSOL, ON_GPU=.TRUE.) ! MACC aerosols
ELSE
  CALL AEROSOL_FIELD%INIT(NBLKS, NRPROMA, 1, NFLEVG, 6, ON_GPU=.TRUE.) ! Tegen climatology
ENDIF
CALL AEROSOL_FIELD%UPDATE_AEROSOL(AEROSOL)
CALL FLUX_FIELD%INIT(NBLKS, YRADIATION%RAD_CONFIG, 1, NRPROMA, NFLEVG, ON_GPU=.TRUE.)
CALL FLUX_FIELD%UPDATE_FLUX(FLUX)

CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 3, F_iamu0)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 4, F_iemiss)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 5, F_its)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 6, F_islm)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 7, F_iccnl)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 8, F_iccno)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 11, F_igelam)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 12, F_igemu)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 15, F_iald)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 16, F_ialp)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 17, F_iti)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 18, F_ipr)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 20, F_iwv)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 21, F_iclc)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 22, F_ilwa)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 23, F_iiwa)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 24, F_iswa)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 25, F_irwa)
IF(lrayfm) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 28, F_ioz)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 31, F_iaprs)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 32, F_ihti)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 33, F_ire_liq)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 34, F_ire_ice)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 35, F_ioverlap)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 36, F_iaero)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 37, F_ifrsod)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 38, F_ifrted)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 39, F_ifrsodc)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 40, F_ifrtedc)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 41, F_iemit)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 42, F_isudu)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 43, F_iuvdf)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 44, F_iparf)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 45, F_iparcf)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 46, F_itincf)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 47, F_ifdir)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 49, F_icdir)
IF(lapproxlwupdate) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 50, F_ilwderivative)
IF(lapproxlwupdate) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 51, F_iswdirectband)
IF(lapproxlwupdate) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 52, F_iswdiffuseband)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 53, F_ifrso)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 54, F_iswfc)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 55, F_ifrth)
CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 56, F_ilwfc)
IF(ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 57, F_iaer)
IF(ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 58, F_ioz)
IF(ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 59, F_iico2)
IF(ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 60, F_iich4)
IF(ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 61, F_iin2o)
IF(ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 62, F_ino2)
IF(ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 63, F_ic11)
IF(ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 64, F_ic12)
IF(ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 65, F_ic22)
IF(ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 66, F_icl4)
IF(.not.ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 68, F_iaer)
IF(.not.(ldiagforcing.or.lrayfm)) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 69, F_ioz)
IF(.not.ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 70, F_iico2)
IF(.not.ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 71, F_iich4)
IF(.not.ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 72, F_iin2o)
IF(.not.ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 73, F_ino2)
IF(.not.ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 74, F_ic11)
IF(.not.ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 75, F_ic12)
IF(.not.ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 76, F_ic22)
IF(.not.ldiagforcing) CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 77, F_icl4)


! Copy ZRGP_FIELDS field stack to device
CALL ZRGP_FIELDS%FIELD_WRAPPER%SYNC_DEVICE_RDWR()

CALL F_iamu0%GET_DEVICE_DATA_RDONLY(P_iamu0)
CALL F_iemiss%GET_DEVICE_DATA_RDONLY(P_iemiss)
CALL F_its%GET_DEVICE_DATA_RDONLY(P_its)
CALL F_islm%GET_DEVICE_DATA_RDONLY(P_islm)
CALL F_iccnl%GET_DEVICE_DATA_RDONLY(P_iccnl)
CALL F_iccno%GET_DEVICE_DATA_RDONLY(P_iccno)
CALL F_igelam%GET_DEVICE_DATA_RDONLY(P_igelam)
CALL F_igemu%GET_DEVICE_DATA_RDONLY(P_igemu)
CALL F_iald%GET_DEVICE_DATA_RDONLY(P_iald)
CALL F_ialp%GET_DEVICE_DATA_RDONLY(P_ialp)
CALL F_iti%GET_DEVICE_DATA_RDONLY(P_iti)
CALL F_ipr%GET_DEVICE_DATA_RDONLY(P_ipr)
CALL F_iwv%GET_DEVICE_DATA_RDONLY(P_iwv)
CALL F_iclc%GET_DEVICE_DATA_RDONLY(P_iclc)
CALL F_ilwa%GET_DEVICE_DATA_RDONLY(P_ilwa)
CALL F_iiwa%GET_DEVICE_DATA_RDONLY(P_iiwa)
CALL F_iswa%GET_DEVICE_DATA_RDONLY(P_iswa)
CALL F_irwa%GET_DEVICE_DATA_RDONLY(P_irwa)
IF(lrayfm) CALL F_ioz%GET_DEVICE_DATA_RDONLY(P_ioz)
CALL F_iaprs%GET_DEVICE_DATA_RDONLY(P_iaprs)
CALL F_ihti%GET_DEVICE_DATA_RDONLY(P_ihti)
CALL F_ire_liq%GET_DEVICE_DATA_RDONLY(P_ire_liq)
CALL F_ire_ice%GET_DEVICE_DATA_RDONLY(P_ire_ice)
CALL F_ioverlap%GET_DEVICE_DATA_RDONLY(P_ioverlap)

CALL F_iaero%GET_DEVICE_DATA_RDWR(P_iaero)
CALL F_ifrsod%GET_DEVICE_DATA_RDWR(P_ifrsod)
CALL F_ifrted%GET_DEVICE_DATA_RDWR(P_ifrted)
CALL F_ifrsodc%GET_DEVICE_DATA_RDWR(P_ifrsodc)
CALL F_ifrtedc%GET_DEVICE_DATA_RDWR(P_ifrtedc)
CALL F_iemit%GET_DEVICE_DATA_RDWR(P_iemit)
CALL F_isudu%GET_DEVICE_DATA_RDWR(P_isudu)
CALL F_iuvdf%GET_DEVICE_DATA_RDWR(P_iuvdf)
CALL F_iparf%GET_DEVICE_DATA_RDWR(P_iparf)
CALL F_iparcf%GET_DEVICE_DATA_RDWR(P_iparcf)
CALL F_itincf%GET_DEVICE_DATA_RDWR(P_itincf)
CALL F_ifdir%GET_DEVICE_DATA_RDWR(P_ifdir)
CALL F_icdir%GET_DEVICE_DATA_RDWR(P_icdir)
IF(lapproxlwupdate) CALL F_ilwderivative%GET_DEVICE_DATA_RDWR(P_ilwderivative)
IF(lapproxlwupdate) CALL F_iswdirectband%GET_DEVICE_DATA_RDWR(P_iswdirectband)
IF(lapproxlwupdate) CALL F_iswdiffuseband%GET_DEVICE_DATA_RDWR(P_iswdiffuseband)
CALL F_ifrso%GET_DEVICE_DATA_RDWR(P_ifrso)
CALL F_iswfc%GET_DEVICE_DATA_RDWR(P_iswfc)
CALL F_ifrth%GET_DEVICE_DATA_RDWR(P_ifrth)
CALL F_ilwfc%GET_DEVICE_DATA_RDWR(P_ilwfc)
IF(ldiagforcing) CALL F_iaer%GET_DEVICE_DATA_RDWR(P_iaer)
IF(ldiagforcing) CALL F_ioz%GET_DEVICE_DATA_RDWR(P_ioz)
IF(ldiagforcing) CALL F_iico2%GET_DEVICE_DATA_RDWR(P_iico2)
IF(ldiagforcing) CALL F_iich4%GET_DEVICE_DATA_RDWR(P_iich4)
IF(ldiagforcing) CALL F_iin2o%GET_DEVICE_DATA_RDWR(P_iin2o)
IF(ldiagforcing) CALL F_ino2%GET_DEVICE_DATA_RDWR(P_ino2)
IF(ldiagforcing) CALL F_ic11%GET_DEVICE_DATA_RDWR(P_ic11)
IF(ldiagforcing) CALL F_ic12%GET_DEVICE_DATA_RDWR(P_ic12)
IF(ldiagforcing) CALL F_ic22%GET_DEVICE_DATA_RDWR(P_ic22)
IF(ldiagforcing) CALL F_icl4%GET_DEVICE_DATA_RDWR(P_icl4)

IF(.not.ldiagforcing) CALL F_iaer%GET_DEVICE_DATA_RDWR(P_iaer)
IF(.not.(ldiagforcing.or.lrayfm)) CALL F_ioz%GET_DEVICE_DATA_RDWR(P_ioz)
IF(.not.ldiagforcing) CALL F_iico2%GET_DEVICE_DATA_RDWR(P_iico2)
IF(.not.ldiagforcing) CALL F_iich4%GET_DEVICE_DATA_RDWR(P_iich4)
IF(.not.ldiagforcing) CALL F_iin2o%GET_DEVICE_DATA_RDWR(P_iin2o)
IF(.not.ldiagforcing) CALL F_ino2%GET_DEVICE_DATA_RDWR(P_ino2)
IF(.not.ldiagforcing) CALL F_ic11%GET_DEVICE_DATA_RDWR(P_ic11)
IF(.not.ldiagforcing) CALL F_ic12%GET_DEVICE_DATA_RDWR(P_ic12)
IF(.not.ldiagforcing) CALL F_ic22%GET_DEVICE_DATA_RDWR(P_ic22)
IF(.not.ldiagforcing) CALL F_icl4%GET_DEVICE_DATA_RDWR(P_icl4)

!$ACC ENTER DATA COPYIN(YRADIATION, YRADIATION%RAD_CONFIG)
#ifdef HAVE_ACC
CALL YRADIATION%RAD_CONFIG%CREATE_DEVICE()
CALL SINGLE_LEVEL_FIELD%ATTACH()
CALL THERMODYNAMICS_FIELD%ATTACH()
CALL GAS_FIELD%ATTACH()
CALL YLCLOUD_FIELD%ATTACH()
CALL AEROSOL_FIELD%ATTACH()
CALL FLUX_FIELD%ATTACH()
#endif

!$ACC DATA COPYIN(KIDIA, KFDIA, NRPROMA, ISEED) &
!$ACC    & PRESENT( &
!$ACC           &  P_IAMU0, P_ITS, P_IALD, P_IALP, &
!$ACC           &  P_IEMISS, &
!$ACC           &  P_ICCNL, P_ICCNO, &
!$ACC           &  P_IGELAM,P_IGEMU, P_ISLM, &
!$ACC           &  P_IPR, P_ITI, &
!$ACC           &  P_IAPRS,P_IHTI, &
!$ACC           &  P_IWV,P_IICO2,P_IICH4,P_IIN2O, &
!$ACC           &  P_INO2,P_IC11,P_IC12, P_IC22, &
!$ACC           &  P_ICL4,P_IOZ, &
!$ACC           &  P_ICLC,P_ILWA,P_IIWA,P_IRWA, &
!$ACC           &  P_ISWA, &
!$ACC           &  P_IAER, P_IAERO, &
!$ACC           &  P_IFRSO,P_IFRTH,P_ISWFC,P_ILWFC,&
!$ACC           &  P_IFRSOD,P_IFRTED, &
!$ACC           &  P_IFRSODC,P_IFRTEDC,&
!$ACC           &  P_IFDIR,P_ICDIR,P_ISUDU, &
!$ACC           &  P_IUVDF,P_IPARF, &
!$ACC           &  P_IPARCF,P_ITINCF, &
!$ACC           &  P_IEMIT,P_ILWDERIVATIVE, &
!$ACC           &  P_ISWDIFFUSEBAND,P_ISWDIRECTBAND, &
!$ACC           &  P_IRE_LIQ, P_IRE_ICE, P_IOVERLAP, &
!$ACC           &  YRADIATION, YRADIATION%RAD_CONFIG, &
!$ACC           &  SINGLE_LEVEL_FIELD, &
!$ACC           &  THERMODYNAMICS_FIELD, &
!$ACC           &  GAS_FIELD, &
!$ACC           &  YLCLOUD_FIELD, &
!$ACC           &  AEROSOL_FIELD, &
!$ACC           &  FLUX_FIELD &
!$ACC           &  )

!$ACC PARALLEL LOOP GANG VECTOR  PRIVATE(SINGLE_LEVEL,THERMODYNAMICS,GAS,YLCLOUD,AEROSOL,FLUX)
DO JKGLO=1,NGPTOT,NRPROMA
    KIDIA=1
    KFDIA=MIN(NRPROMA,NGPTOT-JKGLO+1)
    IBL=(JKGLO-1)/NRPROMA+1

    ! Associate device pointers
    CALL SINGLE_LEVEL_ASSOCIATE_DEVICE_POINTERS(SINGLE_LEVEL_FIELD, SINGLE_LEVEL, IBL)
    CALL THERMODYNAMICS_ASSOCIATE_DEVICE_POINTERS(THERMODYNAMICS_FIELD, THERMODYNAMICS, IBL)
    CALL GAS_ASSOCIATE_DEVICE_POINTERS(GAS_FIELD, GAS, IBL)
    CALL CLOUD_ASSOCIATE_DEVICE_POINTERS(YLCLOUD_FIELD, YLCLOUD, IBL)
    CALL AEROSOL_ASSOCIATE_DEVICE_POINTERS(AEROSOL_FIELD, AEROSOL, IBL)
    CALL FLUX_ASSOCIATE_DEVICE_POINTERS(FLUX_FIELD, FLUX, IBL)

    ! Call the ECRAD radiation scheme
    CALL RADIATION_SCHEME &
        & (YRADIATION, &
        &  KIDIA, KFDIA, NRPROMA, &                       ! startcol, endcol, ncol
        &  NFLEVG, KAEROSOL, &
        &  PSOLAR_IRRADIANCE, &                               ! solar_irrad
        &  P_IAMU0(:,IBL), P_ITS(:,IBL), P_IALD(:,:,IBL), P_IALP(:,:,IBL), &
        &  P_IEMISS(:,:,IBL), &
        &  P_ICCNL(:,IBL), P_ICCNO(:,IBL), &
        &  P_IGELAM(:,IBL),P_IGEMU(:,IBL), P_ISLM(:,IBL), &
        &  P_IPR(:,:,IBL), P_ITI(:,:,IBL), &
        &  P_IAPRS(:,:,IBL),P_IHTI(:,:,IBL), &
        &  P_IWV(:,:,IBL),P_IICO2(:,:,IBL),P_IICH4(:,:,IBL),P_IIN2O(:,:,IBL), &
        &  P_INO2(:,:,IBL),P_IC11(:,:,IBL),P_IC12(:,:,IBL), P_IC22(:,:,IBL), &
        &  P_ICL4(:,:,IBL),P_IOZ(:,:,IBL), &
        &  P_ICLC(:,:,IBL),P_ILWA(:,:,IBL),P_IIWA(:,:,IBL),P_IRWA(:,:,IBL), &
        &  P_ISWA(:,:,IBL), &
        &  P_IAER(:,:,IBL), P_IAERO(:,:,IBL), &
        ! Flux outputs
        &  P_IFRSO(:,:,IBL),P_IFRTH(:,:,IBL),P_ISWFC(:,:,IBL),P_ILWFC(:,:,IBL),&
        &  P_IFRSOD(:,IBL),P_IFRTED(:,:,IBL), &
        &  P_IFRSODC(:,IBL),P_IFRTEDC(:,IBL),&
        &  P_IFDIR(:,IBL),P_ICDIR(:,IBL),P_ISUDU(:,IBL), &
        &  P_IUVDF(:,IBL),P_IPARF(:,IBL), &
        &  P_IPARCF(:,IBL),P_ITINCF(:,IBL), &
        &  P_IEMIT(:,IBL),P_ILWDERIVATIVE(:,:,IBL), &
        &  P_ISWDIFFUSEBAND(:,:,IBL),P_ISWDIRECTBAND(:,:,IBL) &
        &, SINGLE_LEVEL &
        &, THERMODYNAMICS &
        &, GAS &
        &, YLCLOUD &
        &, AEROSOL &
        &, FLUX &
        ! OPTIONAL ARGUMENTS
#ifdef BITIDENTITY_TESTING
        &  , PRE_LIQ=P_IRE_LIQ(:,:,IBL), PRE_ICE=P_IRE_ICE(:,:,IBL) &
        &  , PCLOUD_OVERLAP=P_IOVERLAP(:,:,IBL) & !, ISEED=ISEED(:,IBL) &
#endif
        &  )

END DO

!$ACC END DATA
!$ACC EXIT DATA DELETE(YRADIATION, YRADIATION%RAD_CONFIG)

#ifdef HAVE_ACC
CALL YRADIATION%RAD_CONFIG%DELETE_DEVICE()
#endif

! Copy ZRGP_FIELDS field stack back to host
CALL ZRGP_FIELDS%FIELD_WRAPPER%SYNC_HOST_RDWR()

END ASSOCIATE
END ASSOCIATE

CALL SINGLE_LEVEL_FIELD%FINAL()
CALL THERMODYNAMICS_FIELD%FINAL()
CALL GAS_FIELD%FINAL()
CALL YLCLOUD_FIELD%FINAL()
CALL AEROSOL_FIELD%FINAL()
CALL FLUX_FIELD%FINAL()

IF (LHOOK) CALL DR_HOOK('RADIATION_SCHEME_LAYER_LOKI',1,ZHOOK_HANDLE)

END SUBROUTINE RADIATION_SCHEME_LAYER_LOKI


END MODULE RADIATION_SCHEME_LAYER_MOD
