! (C) Copyright 2015- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
!
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.





MODULE RADIATION_SCHEME_LAYER_MOD

IMPLICIT NONE

CONTAINS

SUBROUTINE RADIATION_SCHEME_LAYER &
     & (YRADIATION, ZRGP_FIELDS, NGPTOT, NPROMA, NFLEVG, KAEROSOL, &
     &  PSOLAR_IRRADIANCE, IVERBOSE, &
     ! OPTIONAL ARGUMENT for bit-identical results in tests
     &  ISEED)

USE FIELD_MODULE   , ONLY : FIELD_2RB, FIELD_3RB
USE FIELD_FACTORY_MODULE

! Modules from ifs or ifsaux libraries
USE PARKIND1                , ONLY : JPIM, JPRB, JPRD
USE YOMHOOK                 , ONLY : LHOOK, DR_HOOK, JPHOOK
USE RADIATION_SETUP         , ONLY : TRADIATION
USE RADIATION_IO            , ONLY : NULERR
USE IFS_BLOCKING            , ONLY : RADINTG_ZRGP_TYPE
USE RADIATION_FIELD_TYPE_MODULE  , ONLY : SINGLE_LEVEL_FIELD_TYPE, &
                                        & THERMODYNAMICS_FIELD_TYPE

! Modules from radiation
USE RADIATION_SINGLE_LEVEL, ONLY: SINGLE_LEVEL_TYPE
USE RADIATION_THERMODYNAMICS, ONLY: THERMODYNAMICS_TYPE

IMPLICIT NONE

! INPUT ARGUMENTS

TYPE(TRADIATION), INTENT(IN)    :: YRADIATION
TYPE(RADINTG_ZRGP_TYPE), INTENT(INOUT) :: ZRGP_FIELDS

! *** Array dimensions and ranges
INTEGER(KIND=JPIM),INTENT(IN)   :: NGPTOT   ! Number of columns
INTEGER(KIND=JPIM),INTENT(IN)   :: NPROMA   ! Number of columns
INTEGER(KIND=JPIM),INTENT(IN)   :: NFLEVG   ! Number of levels
INTEGER(KIND=JPIM),INTENT(IN)   :: KAEROSOL ! Number of aerosol types

! *** Single-level fields
REAL(KIND=JPRB),   INTENT(IN)   :: PSOLAR_IRRADIANCE ! (W m-2)

INTEGER,           INTENT(IN)   :: IVERBOSE

! Optional input argument (Added for validating against ecrad standalone!)
INTEGER,           INTENT(IN), OPTIONAL :: ISEED(:,:)

INTEGER(KIND=JPIM) :: KIDIA, KFDIA, IBL, JKGLO, NBLKS

! Single level field type and type
TYPE(SINGLE_LEVEL_FIELD_TYPE) :: SINGLE_LEVEL_FIELD
TYPE(SINGLE_LEVEL_TYPE) :: SINGLE_LEVEL
TYPE(THERMODYNAMICS_FIELD_TYPE) :: THERMODYNAMICS_FIELD
TYPE(THERMODYNAMICS_TYPE) :: THERMODYNAMICS

! Field object pointers
CLASS(FIELD_2RB), POINTER :: FIELD_2D => NULL()
CLASS(FIELD_3RB), POINTER :: FIELD_3D => NULL()

! Field pointers for each field in ZRGP
CLASS(FIELD_2RB), POINTER :: PFIELD_igi => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_igi(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_iamu0 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iamu0(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_its => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_its(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_islm => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_islm(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_iccnl => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iccnl(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_ibas => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ibas(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_itop => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_itop(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_igelam => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_igelam(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_igemu => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_igemu(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_iclon => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iclon(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_islon => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_islon(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_ifrsod => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrsod(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_ifrted => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrted(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_ifrsodc => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrsodc(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_ifrtedc => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrtedc(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_iemit => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iemit(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_isudu => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_isudu(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_iuvdf => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iuvdf(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_iparf => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iparf(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_iparcf => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iparcf(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_itincf => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_itincf(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_ifdir => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifdir(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_ifdif => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifdif(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_icdir => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_icdir(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_igix => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_igix(:) => NULL()
CLASS(FIELD_2RB), POINTER :: PFIELD_iccno => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iccno(:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_iemiss => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iemiss(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_iald => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iald(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_ialp => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ialp(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_iti => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iti(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_ipr => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ipr(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_iqs => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iqs(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_iwv => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iwv(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_iclc => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iclc(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_ilwa => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ilwa(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_iiwa => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iiwa(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_iswa => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iswa(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_irwa => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_irwa(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_irra => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_irra(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_idp => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_idp(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_ioz => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ioz(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_ihpr => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ihpr(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_iaprs => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iaprs(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_ihti => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ihti(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_iaero => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iaero(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_ilwderivative => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ilwderivative(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_iswdirectband => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iswdirectband(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_iswdiffuseband => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iswdiffuseband(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_ifrso => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrso(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_iswfc => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iswfc(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_ifrth => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ifrth(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_ilwfc => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ilwfc(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_iaer => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iaer(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_iico2 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iico2(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_iich4 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iich4(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_iin2o => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_iin2o(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_ino2 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ino2(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_ic11 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ic11(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_ic12 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ic12(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_ic22 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ic22(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_icl4 => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_icl4(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_ire_liq => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ire_liq(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_ire_ice => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ire_ice(:,:) => NULL()
CLASS(FIELD_3RB), POINTER :: PFIELD_ioverlap => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P_ioverlap(:,:) => NULL()

#include "radiation_scheme.intfb.h"


IF(iverbose>4) THEN ! igi
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 1, PFIELD_igi)
  CALL PFIELD_igi%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! iamu0
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 2, PFIELD_iamu0)
  CALL PFIELD_iamu0%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! iemiss
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 3, PFIELD_iemiss)
  CALL PFIELD_iemiss%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! its
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 4, PFIELD_its)
  CALL PFIELD_its%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! islm
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 5, PFIELD_islm)
  CALL PFIELD_islm%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! iccnl
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 6, PFIELD_iccnl)
  CALL PFIELD_iccnl%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! ibas
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 7, PFIELD_ibas)
  CALL PFIELD_ibas%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! itop
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 8, PFIELD_itop)
  CALL PFIELD_itop%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! igelam
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 9, PFIELD_igelam)
  CALL PFIELD_igelam%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! igemu
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 10, PFIELD_igemu)
  CALL PFIELD_igemu%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! iclon
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 11, PFIELD_iclon)
  CALL PFIELD_iclon%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! islon
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 12, PFIELD_islon)
  CALL PFIELD_islon%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! iald
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 13, PFIELD_iald)
  CALL PFIELD_iald%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! ialp
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 14, PFIELD_ialp)
  CALL PFIELD_ialp%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! iti
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 15, PFIELD_iti)
  CALL PFIELD_iti%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! ipr
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 16, PFIELD_ipr)
  CALL PFIELD_ipr%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! iqs
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 17, PFIELD_iqs)
  CALL PFIELD_iqs%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! iwv
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 18, PFIELD_iwv)
  CALL PFIELD_iwv%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! iclc
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 19, PFIELD_iclc)
  CALL PFIELD_iclc%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! ilwa
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 20, PFIELD_ilwa)
  CALL PFIELD_ilwa%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! iiwa
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 21, PFIELD_iiwa)
  CALL PFIELD_iiwa%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! iswa
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 22, PFIELD_iswa)
  CALL PFIELD_iswa%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! irwa
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 23, PFIELD_irwa)
  CALL PFIELD_irwa%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! irra
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 24, PFIELD_irra)
  CALL PFIELD_irra%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! idp
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 25, PFIELD_idp)
  CALL PFIELD_idp%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! ioz
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 26, PFIELD_ioz)
  CALL PFIELD_ioz%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! ihpr
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 27, PFIELD_ihpr)
  CALL PFIELD_ihpr%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! iaprs
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 28, PFIELD_iaprs)
  CALL PFIELD_iaprs%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! ihti
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 29, PFIELD_ihti)
  CALL PFIELD_ihti%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! iaero
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 30, PFIELD_iaero)
  CALL PFIELD_iaero%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! ifrsod
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 31, PFIELD_ifrsod)
  CALL PFIELD_ifrsod%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! ifrted
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 32, PFIELD_ifrted)
  CALL PFIELD_ifrted%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! ifrsodc
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 33, PFIELD_ifrsodc)
  CALL PFIELD_ifrsodc%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! ifrtedc
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 34, PFIELD_ifrtedc)
  CALL PFIELD_ifrtedc%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! iemit
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 35, PFIELD_iemit)
  CALL PFIELD_iemit%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! isudu
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 36, PFIELD_isudu)
  CALL PFIELD_isudu%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! iuvdf
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 37, PFIELD_iuvdf)
  CALL PFIELD_iuvdf%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! iparf
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 38, PFIELD_iparf)
  CALL PFIELD_iparf%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! iparcf
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 39, PFIELD_iparcf)
  CALL PFIELD_iparcf%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! itincf
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 40, PFIELD_itincf)
  CALL PFIELD_itincf%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! ifdir
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 41, PFIELD_ifdir)
  CALL PFIELD_ifdir%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! ifdif
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 42, PFIELD_ifdif)
  CALL PFIELD_ifdif%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! icdir
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 43, PFIELD_icdir)
  CALL PFIELD_icdir%SYNC_HOST_RDWR()
END IF

IF(yradiation%yrerad%lapproxlwupdate) THEN ! ilwderivative
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 44, PFIELD_ilwderivative)
  CALL PFIELD_ilwderivative%SYNC_HOST_RDWR()
END IF

IF(yradiation%yrerad%lapproxswupdate) THEN ! iswdirectband
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 45, PFIELD_iswdirectband)
  CALL PFIELD_iswdirectband%SYNC_HOST_RDWR()
END IF

IF(yradiation%yrerad%lapproxswupdate) THEN ! iswdiffuseband
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 46, PFIELD_iswdiffuseband)
  CALL PFIELD_iswdiffuseband%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! ifrso
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 47, PFIELD_ifrso)
  CALL PFIELD_ifrso%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! iswfc
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 48, PFIELD_iswfc)
  CALL PFIELD_iswfc%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! ifrth
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 49, PFIELD_ifrth)
  CALL PFIELD_ifrth%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! ilwfc
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 50, PFIELD_ilwfc)
  CALL PFIELD_ilwfc%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! iaer
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 51, PFIELD_iaer)
  CALL PFIELD_iaer%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! iico2
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 52, PFIELD_iico2)
  CALL PFIELD_iico2%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! iich4
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 53, PFIELD_iich4)
  CALL PFIELD_iich4%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! iin2o
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 54, PFIELD_iin2o)
  CALL PFIELD_iin2o%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! ino2
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 55, PFIELD_ino2)
  CALL PFIELD_ino2%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! ic11
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 56, PFIELD_ic11)
  CALL PFIELD_ic11%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! ic12
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 57, PFIELD_ic12)
  CALL PFIELD_ic12%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! ic22
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 58, PFIELD_ic22)
  CALL PFIELD_ic22%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! icl4
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 59, PFIELD_icl4)
  CALL PFIELD_icl4%SYNC_HOST_RDWR()
END IF

IF(iverbose>4) THEN ! igix
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 60, PFIELD_igix)
  CALL PFIELD_igix%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! iccno
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 61, PFIELD_iccno)
  CALL PFIELD_iccno%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! ire_liq
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 62, PFIELD_ire_liq)
  CALL PFIELD_ire_liq%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! ire_ice
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 63, PFIELD_ire_ice)
  CALL PFIELD_ire_ice%SYNC_HOST_RDWR()
END IF

IF(.true.) THEN ! ioverlap
  CALL GET_STACK_MEMBER(ZRGP_FIELDS%FIELD_WRAPPER, 64, PFIELD_ioverlap)
  CALL PFIELD_ioverlap%SYNC_HOST_RDWR()
END IF


NBLKS = (NGPTOT-1)/NPROMA + 1
CALL SINGLE_LEVEL_FIELD%INIT(NBLKS, NPROMA, YRADIATION%YRERAD%NSW, YRADIATION%YRERAD%NLWEMISS, &
     &                      USE_SW_ALBEDO_DIRECT=.TRUE.)
CALL THERMODYNAMICS_FIELD%INIT(NBLKS, NPROMA, NFLEVG, USE_H2O_SAT=.TRUE.)
!$OMP PARALLEL DO SCHEDULE(DYNAMIC,1)&
!$OMP&PRIVATE(JKGLO,KIDIA,KFDIA,IBL) FIRSTPRIVATE(ZRGP_FIELDS, SINGLE_LEVEL_FIELD, SINGLE_LEVEL, THERMODYNAMICS_FIELD, THERMODYNAMICS)
DO JKGLO=1,NGPTOT,NPROMA
    KIDIA=1
    KFDIA=MIN(NPROMA,NGPTOT-JKGLO+1)
    IBL=(JKGLO-1)/NPROMA+1

    ! Update single level type pointers
    CALL SINGLE_LEVEL_FIELD%UPDATE_VIEW(IBL)
    CALL SINGLE_LEVEL_FIELD%UPDATE_SINGLE_LEVEL(SINGLE_LEVEL)
    CALL THERMODYNAMICS_FIELD%UPDATE_VIEW(IBL)
    CALL THERMODYNAMICS_FIELD%UPDATE_THERMODYNAMICS(THERMODYNAMICS)

    ! Create contiguous view pointers for each field in the current block
    IF ( iverbose>4 ) P_igi => PFIELD_igi%GET_VIEW(IBL)
    IF ( .true. ) P_iamu0 => PFIELD_iamu0%GET_VIEW(IBL)
    IF ( .true. ) P_its => PFIELD_its%GET_VIEW(IBL)
    IF ( .true. ) P_islm => PFIELD_islm%GET_VIEW(IBL)
    IF ( .true. ) P_iccnl => PFIELD_iccnl%GET_VIEW(IBL)
    IF ( .true. ) P_ibas => PFIELD_ibas%GET_VIEW(IBL)
    IF ( .true. ) P_itop => PFIELD_itop%GET_VIEW(IBL)
    IF ( .true. ) P_igelam => PFIELD_igelam%GET_VIEW(IBL)
    IF ( .true. ) P_igemu => PFIELD_igemu%GET_VIEW(IBL)
    IF ( .true. ) P_iclon => PFIELD_iclon%GET_VIEW(IBL)
    IF ( .true. ) P_islon => PFIELD_islon%GET_VIEW(IBL)
    IF ( .true. ) P_ifrsod => PFIELD_ifrsod%GET_VIEW(IBL)
    IF ( .true. ) P_ifrted => PFIELD_ifrted%GET_VIEW(IBL)
    IF ( .true. ) P_ifrsodc => PFIELD_ifrsodc%GET_VIEW(IBL)
    IF ( .true. ) P_ifrtedc => PFIELD_ifrtedc%GET_VIEW(IBL)
    IF ( .true. ) P_iemit => PFIELD_iemit%GET_VIEW(IBL)
    IF ( .true. ) P_isudu => PFIELD_isudu%GET_VIEW(IBL)
    IF ( .true. ) P_iuvdf => PFIELD_iuvdf%GET_VIEW(IBL)
    IF ( .true. ) P_iparf => PFIELD_iparf%GET_VIEW(IBL)
    IF ( .true. ) P_iparcf => PFIELD_iparcf%GET_VIEW(IBL)
    IF ( .true. ) P_itincf => PFIELD_itincf%GET_VIEW(IBL)
    IF ( .true. ) P_ifdir => PFIELD_ifdir%GET_VIEW(IBL)
    IF ( .true. ) P_ifdif => PFIELD_ifdif%GET_VIEW(IBL)
    IF ( .true. ) P_icdir => PFIELD_icdir%GET_VIEW(IBL)
    IF ( iverbose>4 ) P_igix => PFIELD_igix%GET_VIEW(IBL)
    IF ( .true. ) P_iccno => PFIELD_iccno%GET_VIEW(IBL)
    IF ( .true. ) P_iemiss => PFIELD_iemiss%GET_VIEW(IBL)
    IF ( .true. ) P_iald => PFIELD_iald%GET_VIEW(IBL)
    IF ( .true. ) P_ialp => PFIELD_ialp%GET_VIEW(IBL)
    IF ( .true. ) P_iti => PFIELD_iti%GET_VIEW(IBL)
    IF ( .true. ) P_ipr => PFIELD_ipr%GET_VIEW(IBL)
    IF ( .true. ) P_iqs => PFIELD_iqs%GET_VIEW(IBL)
    IF ( .true. ) P_iwv => PFIELD_iwv%GET_VIEW(IBL)
    IF ( .true. ) P_iclc => PFIELD_iclc%GET_VIEW(IBL)
    IF ( .true. ) P_ilwa => PFIELD_ilwa%GET_VIEW(IBL)
    IF ( .true. ) P_iiwa => PFIELD_iiwa%GET_VIEW(IBL)
    IF ( .true. ) P_iswa => PFIELD_iswa%GET_VIEW(IBL)
    IF ( .true. ) P_irwa => PFIELD_irwa%GET_VIEW(IBL)
    IF ( .true. ) P_irra => PFIELD_irra%GET_VIEW(IBL)
    IF ( .true. ) P_idp => PFIELD_idp%GET_VIEW(IBL)
    IF ( .true. ) P_ioz => PFIELD_ioz%GET_VIEW(IBL)
    IF ( .true. ) P_ihpr => PFIELD_ihpr%GET_VIEW(IBL)
    IF ( .true. ) P_iaprs => PFIELD_iaprs%GET_VIEW(IBL)
    IF ( .true. ) P_ihti => PFIELD_ihti%GET_VIEW(IBL)
    IF ( .true. ) P_iaero => PFIELD_iaero%GET_VIEW(IBL)
    IF ( yradiation%yrerad%lapproxlwupdate ) P_ilwderivative => PFIELD_ilwderivative%GET_VIEW(IBL)
    IF ( yradiation%yrerad%lapproxswupdate ) P_iswdirectband => PFIELD_iswdirectband%GET_VIEW(IBL)
    IF ( yradiation%yrerad%lapproxswupdate ) P_iswdiffuseband => PFIELD_iswdiffuseband%GET_VIEW(IBL)
    IF ( .true. ) P_ifrso => PFIELD_ifrso%GET_VIEW(IBL)
    IF ( .true. ) P_iswfc => PFIELD_iswfc%GET_VIEW(IBL)
    IF ( .true. ) P_ifrth => PFIELD_ifrth%GET_VIEW(IBL)
    IF ( .true. ) P_ilwfc => PFIELD_ilwfc%GET_VIEW(IBL)
    IF ( .true. ) P_iaer => PFIELD_iaer%GET_VIEW(IBL)
    IF ( .true. ) P_iico2 => PFIELD_iico2%GET_VIEW(IBL)
    IF ( .true. ) P_iich4 => PFIELD_iich4%GET_VIEW(IBL)
    IF ( .true. ) P_iin2o => PFIELD_iin2o%GET_VIEW(IBL)
    IF ( .true. ) P_ino2 => PFIELD_ino2%GET_VIEW(IBL)
    IF ( .true. ) P_ic11 => PFIELD_ic11%GET_VIEW(IBL)
    IF ( .true. ) P_ic12 => PFIELD_ic12%GET_VIEW(IBL)
    IF ( .true. ) P_ic22 => PFIELD_ic22%GET_VIEW(IBL)
    IF ( .true. ) P_icl4 => PFIELD_icl4%GET_VIEW(IBL)
    IF ( .true. ) P_ire_liq => PFIELD_ire_liq%GET_VIEW(IBL)
    IF ( .true. ) P_ire_ice => PFIELD_ire_ice%GET_VIEW(IBL)
    IF ( .true. ) P_ioverlap => PFIELD_ioverlap%GET_VIEW(IBL)

    ! Call the ECRAD radiation scheme
    CALL RADIATION_SCHEME &
        & (YRADIATION, &
        &  KIDIA, KFDIA, NPROMA, &                       ! startcol, endcol, ncol
        &  NFLEVG, KAEROSOL, &
        &  PSOLAR_IRRADIANCE &                               ! solar_irrad
        &, P_iamu0 &
        &, P_its &
        &, P_iald &
        &, P_ialp &
        &, P_iemiss &
        &, P_iccnl &
        &, P_iccno &
        &, P_igelam &
        &, P_igemu &
        &, P_islm &
        &, P_ipr &
        &, P_iti &
        &, P_iaprs &
        &, P_ihti &
        &, P_iwv &
        &, P_iico2 &
        &, P_iich4 &
        &, P_iin2o &
        &, P_ino2 &
        &, P_ic11 &
        &, P_ic12 &
        &, P_ic22 &
        &, P_icl4 &
        &, P_ioz &
        &, P_iclc &
        &, P_ilwa &
        &, P_iiwa &
        &, P_irwa &
        &, P_iswa &
        &, P_iaer &
        &, P_iaero &
        &, P_ifrso &
        &, P_ifrth &
        &, P_iswfc &
        &, P_ilwfc &
        &, P_ifrsod &
        &, P_ifrted &
        &, P_ifrsodc &
        &, P_ifrtedc &
        &, P_ifdir &
        &, P_icdir &
        &, P_isudu &
        &, P_iuvdf &
        &, P_iparf &
        &, P_iparcf &
        &, P_itincf &
        &, P_iemit &
        &, P_ilwderivative &
        &, P_iswdiffuseband &
        &, P_iswdirectband &
        &, SINGLE_LEVEL &
        &, THERMODYNAMICS &
#ifdef BITIDENTITY_TESTING
        ! To validate results against standalone ecrad, we overwrite effective
        ! radii, cloud overlap and seed with input values
        &, pre_liq=p_ire_liq, pre_ice=p_ire_ice &
        &, pcloud_overlap=p_ioverlap, iseed=iseed(:,ibl) &
#endif
        & )

end do
!$OMP END PARALLEL DO

CALL SINGLE_LEVEL_FIELD%FINAL()
CALL THERMODYNAMICS_FIELD%FINAL()

END SUBROUTINE RADIATION_SCHEME_LAYER

END MODULE RADIATION_SCHEME_LAYER_MOD
